### ISSUE TITLE
Module Won't Load

### ISSUE THREAD

**Issue by AmbushXXVI** [Z3nner/lancer-weapon-fx#7]
When I attempt to enable the Lancer Weapon Fx module, I get an error that JB2A_dnd5e is not enabled. I've got the Patreon Complete Collection installed and enabled on this world. Does this not work for some reason with the paid Patreon content?

**Comment by Gazkhan** [comment]
@dodgepong I've had a quick look at this and since you're using the Sequencer database paths in the macros, it will be compatible with both the free pack and the Patreon pack.
So, instead of a hard dependency from the module.json, you could maybe add something like this to your main script ``WeaponFX.js`` ? 

```js 
Hooks.on('ready', () => {
    if (!game.modules.get('jb2a_patreon')?.active && !game.modules.get('JB2A_DnD5e')?.active){
        ui.notifications.error("You need either the Free or the Patreon version of JB2A for this module to work properly");
    }
})
```
It's just an example though, I'm sure you can do much better than me ! 😅

**Comment by dodgepong** [comment]
I'm not the maintainer of the module but I think Zenn is pretty open to pull requests.

**Comment by Gazkhan** [comment]
Oh ok thanks. I've gone ahead and created a PR. Take it or leave it though, no hard feelings 😆
